services:
  rev-proxy:
    image: traefik:3
    command:
      - "--api.insecure=true"
      # - "--log.level=DEBUG"
      - "--log.filePath=/logs/traefik.log"
      - "--log.maxage=30"
      - "--log.compress=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.websecure.address=:443"
      - "--entryPoints.websecure.http.tls=true"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - proxylogs:/logs
      - letsencrypt:/letsencrypt
  web:
    build: .
    environment:
      HTTPS: false
      PROD: true
    # deploy:
    #   mode: replicated
    #   replicas: 2
    volumes:
      - weblogs:/usr/local/awt/src/logs
      - ./src/db.sqlite3:/usr/local/awt/src/db.sqlite3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`appu.ltd`)"
      - "traefik.http.services.web.loadbalancer.server.port=80"
      - "traefik.http.routers.web.entrypoints=websecure"
      - "traefik.http.routers.web.tls=true"

volumes:
  proxylogs:
    driver: local
  weblogs:
    driver: local
  letsencrypt:
    driver: local
