# Generated by Django 4.0.1 on 2022-01-20 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas', '0006_alter_locality_options_alter_postalcode_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='last_update',
            field=models.DateTimeField(verbose_name='Last update'),
        ),
    ]
