# Generated by Django 4.0.1 on 2022-01-20 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gas', '0007_alter_station_last_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='last_update',
        ),
    ]
