# Generated by Django 4.1.1 on 2022-09-30 07:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gas", "0008_remove_station_last_update"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="locality",
            name="id",
        ),
        migrations.RemoveField(
            model_name="province",
            name="id",
        ),
        migrations.AddField(
            model_name="locality",
            name="id_mun",
            field=models.IntegerField(
                default=0,
                help_text="ID of the municipality",
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="Municipality ID",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="province",
            name="id_prov",
            field=models.IntegerField(
                default=0,
                help_text="ID of the province",
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="Province ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="station",
            name="postal_code",
            field=models.IntegerField(
                default=10000,
                validators=[
                    django.core.validators.MinValueValidator(9999),
                    django.core.validators.MaxValueValidator(99999),
                ],
                verbose_name="Postal code",
            ),
        ),
        migrations.DeleteModel(
            name="PostalCode",
        ),
    ]
