# Generated by Django 4.2.1 on 2023-05-16 19:35

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("gas", "0012_remove_station_gasoleo_b"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="station",
            name="gasoleo_a",
        ),
        migrations.RemoveField(
            model_name="station",
            name="gasolina_95",
        ),
        migrations.RemoveField(
            model_name="station",
            name="gasolina_98",
        ),
        migrations.RemoveField(
            model_name="station",
            name="glp",
        ),
        migrations.CreateModel(
            name="StationPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True, db_index=True)),
                (
                    "gasoleo_a",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0"),
                        max_digits=4,
                        verbose_name="Gasoleo A",
                    ),
                ),
                (
                    "gasolina_95",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0"),
                        max_digits=4,
                        verbose_name="Gasolina 95",
                    ),
                ),
                (
                    "gasolina_98",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0"),
                        max_digits=4,
                        verbose_name="Gasolina 98",
                    ),
                ),
                (
                    "glp",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0"),
                        max_digits=4,
                        verbose_name="GLP",
                    ),
                ),
                (
                    "id_eess",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="gas.station"
                    ),
                ),
            ],
            options={
                "verbose_name": "Gas station price",
                "verbose_name_plural": "Gas station prices",
                "ordering": ["id_eess", "date"],
            },
        ),
        migrations.AddConstraint(
            model_name="stationprice",
            constraint=models.UniqueConstraint(
                fields=("id_eess", "date"), name="unique_station_date_combination"
            ),
        ),
    ]
