# Generated by Django 4.2.1 on 2023-05-16 22:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gas", "0013_create_prices_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="station",
            name="last_update",
            field=models.DateTimeField(auto_now=True, verbose_name="Last update"),
        ),
    ]
