# Generated by Django 4.2.1 on 2023-05-17 17:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gas", "0015_rename_stationprice_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stationprice",
            name="price_g95",
            field=models.DecimalField(
                decimal_places=3,
                default=None,
                max_digits=4,
                null=True,
                verbose_name="Gasolina 95",
            ),
        ),
        migrations.AlterField(
            model_name="stationprice",
            name="price_g98",
            field=models.DecimalField(
                decimal_places=3,
                default=None,
                max_digits=4,
                null=True,
                verbose_name="Gasolina 98",
            ),
        ),
        migrations.AlterField(
            model_name="stationprice",
            name="price_glp",
            field=models.DecimalField(
                decimal_places=3,
                default=None,
                max_digits=4,
                null=True,
                verbose_name="GLP",
            ),
        ),
        migrations.AlterField(
            model_name="stationprice",
            name="price_goa",
            field=models.DecimalField(
                decimal_places=3,
                default=None,
                max_digits=4,
                null=True,
                verbose_name="Gasoleo A",
            ),
        ),
    ]
