# Generated by Django 4.2.1 on 2023-05-17 19:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gas", "0016_stationprice_allow_null_price"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stationprice",
            options={
                "ordering": ["-date", "station"],
                "verbose_name": "Gas station price",
                "verbose_name_plural": "Gas station prices",
            },
        ),
    ]
