# Generated by Django 4.2.1 on 2023-05-23 11:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gas", "0019_alter_stationprice_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="station",
            name="last_update",
        ),
    ]
