# Generated by Django 4.2.1 on 2023-06-04 21:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gas", "0021_alter_stationprice_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="locality",
            name="id_mun",
            field=models.IntegerField(
                help_text="ID of the locality",
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="Locality ID",
            ),
        ),
    ]
