# Generated by Django 4.2.7 on 2024-03-19 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("gas", "0022_alter_locality_id_mun"),
    ]

    operations = [
        migrations.AddField(
            model_name="stationprice",
            name="price_gob",
            field=models.DecimalField(
                decimal_places=3,
                default=None,
                max_digits=4,
                null=True,
                verbose_name="Gasoleo B",
            ),
        ),
        migrations.AlterField(
            model_name="station",
            name="locality",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="gas.locality"
            ),
        ),
        migrations.AlterField(
            model_name="station",
            name="province",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="gas.province"
            ),
        ),
        migrations.AlterField(
            model_name="stationprice",
            name="price_g95e5",
            field=models.DecimalField(
                decimal_places=3,
                default=None,
                max_digits=4,
                null=True,
                verbose_name="Gasolina 95 E5",
            ),
        ),
        migrations.AlterField(
            model_name="stationprice",
            name="price_g98e5",
            field=models.DecimalField(
                decimal_places=3,
                default=None,
                max_digits=4,
                null=True,
                verbose_name="Gasolina 98 E5",
            ),
        ),
    ]
