# Generated by Django 4.2.7 on 2024-03-19 23:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gas", "0024_alter_station_locality_alter_station_province"),
    ]

    operations = [
        migrations.AddField(
            model_name="stationprice",
            name="price_g95e10",
            field=models.DecimalField(
                decimal_places=3,
                default=None,
                max_digits=4,
                null=True,
                verbose_name="Gasolina 95 E10",
            ),
        ),
        migrations.AddField(
            model_name="stationprice",
            name="price_g95e5_premium",
            field=models.DecimalField(
                decimal_places=3,
                default=None,
                max_digits=4,
                null=True,
                verbose_name="Gasolina 95 E5 Premium",
            ),
        ),
        migrations.AddField(
            model_name="stationprice",
            name="price_g98e10",
            field=models.DecimalField(
                decimal_places=3,
                default=None,
                max_digits=4,
                null=True,
                verbose_name="Gasolina 98 E10",
            ),
        ),
        migrations.AddField(
            model_name="stationprice",
            name="price_gnc",
            field=models.DecimalField(
                decimal_places=3,
                default=None,
                max_digits=4,
                null=True,
                verbose_name="GNC",
            ),
        ),
        migrations.AddField(
            model_name="stationprice",
            name="price_h2",
            field=models.DecimalField(
                decimal_places=3,
                default=None,
                max_digits=4,
                null=True,
                verbose_name="H2",
            ),
        ),
    ]
