# Generated by Django 5.0.6 on 2024-06-29 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas', '0026_alter_station_locality_alter_station_province_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationprice',
            name='price_g95e10',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=5, null=True, verbose_name='Gasolina 95 E10'),
        ),
        migrations.AlterField(
            model_name='stationprice',
            name='price_g95e5',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=5, null=True, verbose_name='Gasolina 95 E5'),
        ),
        migrations.AlterField(
            model_name='stationprice',
            name='price_g95e5_premium',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=5, null=True, verbose_name='Gasolina 95 E5 Premium'),
        ),
        migrations.AlterField(
            model_name='stationprice',
            name='price_g98e10',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=5, null=True, verbose_name='Gasolina 98 E10'),
        ),
        migrations.AlterField(
            model_name='stationprice',
            name='price_g98e5',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=5, null=True, verbose_name='Gasolina 98 E5'),
        ),
        migrations.AlterField(
            model_name='stationprice',
            name='price_glp',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=5, null=True, verbose_name='GLP'),
        ),
        migrations.AlterField(
            model_name='stationprice',
            name='price_gnc',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=5, null=True, verbose_name='GNC'),
        ),
        migrations.AlterField(
            model_name='stationprice',
            name='price_goa',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=5, null=True, verbose_name='Gasoleo A'),
        ),
        migrations.AlterField(
            model_name='stationprice',
            name='price_gob',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=5, null=True, verbose_name='Gasoleo B'),
        ),
        migrations.AlterField(
            model_name='stationprice',
            name='price_h2',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=5, null=True, verbose_name='H2'),
        ),
    ]
