# Generated by Django 4.0.1 on 2022-01-20 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gas', '0005_auto_20220119_2118'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locality',
            options={'ordering': ['name'], 'verbose_name': 'Locality', 'verbose_name_plural': 'Localities'},
        ),
        migrations.AlterModelOptions(
            name='postalcode',
            options={'ordering': ['postal_code'], 'verbose_name': 'Postal code', 'verbose_name_plural': 'Postal codes'},
        ),
        migrations.AlterModelOptions(
            name='province',
            options={'ordering': ['name'], 'verbose_name': 'Province', 'verbose_name_plural': 'Provinces'},
        ),
    ]
