# Generated by Django 4.1.1 on 2022-09-30 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gas", "0009_remove_locality_id_remove_province_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="station",
            name="price_history",
        ),
        migrations.RemoveField(
            model_name="station",
            name="prices",
        ),
        migrations.AddField(
            model_name="station",
            name="gasoleo_a",
            field=models.DecimalField(
                decimal_places=3, default=0, max_digits=4, verbose_name="Gasoleo A"
            ),
        ),
        migrations.AddField(
            model_name="station",
            name="gasoleo_b",
            field=models.DecimalField(
                decimal_places=3, default=0, max_digits=4, verbose_name="Gasoleo B"
            ),
        ),
        migrations.AddField(
            model_name="station",
            name="gasolina_95",
            field=models.DecimalField(
                decimal_places=3, default=0, max_digits=4, verbose_name="Gasolina 95"
            ),
        ),
        migrations.AddField(
            model_name="station",
            name="gasolina_98",
            field=models.DecimalField(
                decimal_places=3, default=0, max_digits=4, verbose_name="Gasolina 98"
            ),
        ),
        migrations.AddField(
            model_name="station",
            name="glp",
            field=models.DecimalField(
                decimal_places=3, default=0, max_digits=4, verbose_name="GLP"
            ),
        ),
    ]
