# Generated by Django 4.2 on 2023-04-23 17:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gas", "0011_alter_station_postal_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="station",
            name="gasoleo_b",
        ),
    ]
