# Generated by Django 4.2.7 on 2023-11-20 00:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mastermind", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="game",
            options={"ordering": ["-created"]},
        ),
        migrations.AlterModelOptions(
            name="guess",
            options={"ordering": ["-created"], "verbose_name_plural": "Guesses"},
        ),
    ]
