# Generated by Django 4.2.7 on 2023-11-20 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("mastermind", "0002_alter_game_options_alter_guess_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="game_id",
            field=models.IntegerField(
                auto_created=True, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="guess",
            name="game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="guesses",
                to="mastermind.game",
            ),
        ),
    ]
