# Generated by Django 4.2.7 on 2024-03-15 20:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mastermind", "0003_remove_game_lost_game_finished"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="finished",
        ),
    ]
