# Generated by Django 4.0.3 on 2022-08-06 20:44

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('gas', '0008_remove_station_last_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='AWTUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('user_email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('preferred_query', models.JSONField(blank=True, default=dict, verbose_name='Preferred query')),
                ('has_activated', models.BooleanField(default=False, verbose_name='Has activated')),
                ('preferred_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gas.station')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['username'],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
