# Generated by Django 4.0.3 on 2022-08-06 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='awtuser',
            name='user_email',
        ),
    ]
