# Generated by Django 4.0.3 on 2022-09-07 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_awtuser_is_enabled_awtuser_is_upgraded'),
    ]

    operations = [
        migrations.AddField(
            model_name='awtuser',
            name='upgrade_uuid',
            field=models.UUIDField(blank=True, null=True, verbose_name='Upgrade UUID'),
        ),
    ]
