# Generated by Django 4.1.1 on 2022-09-09 07:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_awtuser_upgrade_uuid"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="awtuser",
            options={
                "ordering": ["username"],
                "verbose_name": "AWT User",
                "verbose_name_plural": "AWT Users",
            },
        ),
        migrations.AlterField(
            model_name="awtuser",
            name="upgrade_uuid",
            field=models.CharField(
                blank=True,
                max_length=24,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[a-f0-9]{6}-[a-f0-9]{10}-[a-f0-9]{6}$", "Invalid UUID"
                    )
                ],
                verbose_name="Upgrade UUID",
            ),
        ),
    ]
