# Generated by Django 4.0.3 on 2022-08-07 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_awtuser_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='awtuser',
            name='has_activated',
        ),
        migrations.AddField(
            model_name='awtuser',
            name='is_enabled',
            field=models.BooleanField(default=False, verbose_name='Is enabled'),
        ),
    ]
