# Generated by Django 4.0.3 on 2022-09-06 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_awtuser_has_activated_awtuser_is_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='awtuser',
            name='is_enabled',
        ),
        migrations.AddField(
            model_name='awtuser',
            name='is_upgraded',
            field=models.BooleanField(default=False, verbose_name='Upgraded'),
        ),
    ]
