# Generated by Django 4.1.1 on 2022-09-12 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_alter_awtuser_options_alter_awtuser_upgrade_uuid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="awtuser",
            old_name="preferred_query",
            new_name="saved_query",
        ),
        migrations.RenameField(
            model_name="awtuser",
            old_name="preferred_station",
            new_name="saved_station",
        ),
    ]
