# Generated by Django 4.2.1 on 2023-06-04 21:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("gas", "0022_alter_locality_id_mun"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0009_rename_preferred_query_awtuser_saved_query_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedQuery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "term",
                    models.CharField(
                        max_length=100,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Only alphanumeric characters and underscores are allowed.",
                                regex="^[a-zA-Z0-9_]*$",
                            )
                        ],
                    ),
                ),
                (
                    "q_type",
                    models.CharField(
                        choices=[
                            ("locality", "Locality"),
                            ("province", "Province"),
                            ("postal_code", "Postal Code"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "fuel_abbr",
                    models.CharField(
                        choices=[
                            ("GOA", "Diesel"),
                            ("G95E5", "Gasolina 95"),
                            ("G98E5", "Gasolina 98"),
                            ("GLP", "Gases Licuados del Petróleo"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Saved Query",
                "verbose_name_plural": "Saved Queries",
                "ordering": ["user"],
            },
        ),
        migrations.CreateModel(
            name="SavedStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="gas.station"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Saved Station",
                "verbose_name_plural": "Saved Stations",
                "ordering": ["user"],
            },
        ),
        migrations.DeleteModel(
            name="AWTUser",
        ),
    ]
