# Generated by Django 4.2.5 on 2023-09-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0010_savedquery_savedstation_delete_awtuser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="savedquery",
            name="q_type",
            field=models.CharField(
                choices=[
                    ("locality", "Locality"),
                    ("province", "Province"),
                    ("postal_code", "Postal code"),
                ],
                max_length=100,
            ),
        ),
    ]
